version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz
    ### NOTE if you plan to use Stata to analyse the main input file(s) please use --output-format='dta.gz' instead, 
    ### and subsequently open with 'gzuse' in Stata (http://fmwww.bc.edu/RePEc/bocode/g/gzsave.html)

